    "Backup/Restore all teams":"备份所有队伍",
    "Backup all teams from this folder":"备份该文件夹里的所有队伍",
    "Base":"种族值",
    "Import":"导入",
    "Types":"属性",
    "(automatic type)":"自动对应的属性",
    "Hidden Power:":"觉醒力量属性：",
    "You can also set natures by typing \"+\" and \"-\" next to a stat.":"你可以在基础点数框内输入+和-来设定性格",
    "Protip:":"提示：",
    "Nature:":"性格：",
    "Sort":"排序方法",
    "Hide":"隐藏",
    "Dark mode":"夜间模式",
    "Minimum Elo:":"最低Elo积分：",
    "None":"无限制",
    "Search":"搜索",
    "(muted)":"（已静音）",
    "Mute sounds":"全部静音",
    "Effect volume:":"宝可梦叫声音量：",
    "Music volume:":"背景音乐音量：",
    "Notification volume:":"通知提醒音量",
    "(Offline)":"（离线）",
    "Rated battle":"计分战斗",
    "Battle Options":"战斗选项",
    "In this battle":"在这场战斗中",
    "Ignore Spectators":"忽略来自观战者的消息",
    "Ignore Opponent":"忽略来自对手的消息",
    "All battles":"所有战斗中",
    "Ignore nicknames":"忽略宝可梦昵称",
    "Open new battles on the right side":"在右侧开启新战斗窗口",
    "Close":"关闭",
    "Hardcore mode (hide info not shown in-game) (beta)":"硬核模式(隐藏实机无法看到的信息)(测试)",
    "Item:":"道具：",
    "Ability:":"特性：",
    "(before items/abilities/modifiers)":"（不计算道具/特性/加成）",
    "(fainted)":"",
    "Waiting for players...":"等待选手行动...",
    "Spectators ignored.":"观战者消息已经被忽略",
    "Spectators no longer ignored.":"观战者的消息已经不再忽略",
    "Opponent ignored.":"对手的消息已经被忽略",
    "Opponent no longer ignored.":"对手的消息已经不再忽略",
    "Hardcore mode ON: Information not available in-game is now hidden.":"硬核模式开启，实机无法看到的信息已经被隐藏",
    "Hardcore mode OFF: Information not available in-game is now shown.":"硬核模式关闭，实机无法看到的信息将会显示",
    "Nicknames ignored.":"昵称已经被忽略",
    "Nicknames no longer ignored.":"昵称不再被忽略",
    "(fainted)":"（濒死）",
    "Turn":"回合",
    "PSN":"中毒",
    "SLP":"睡眠",
    "PAR":"麻痹",
    "BRN":"灼伤",
    "TOX":"中剧毒",
    "Attack":"攻击",
    "Defense":"防御",
    "Speed":"速度",
    "Next damage: ":"下回合伤害：",
